version: '3'
services:
  client_api:
    depends_on:
      - pds
    networks:
      - pds_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    build:
      dockerfile: dev/Dockerfile.client-api
      context: .
    environment:
      LISTEN_ADDR: ":8080"
      PORT_DOMAIN_SERVICE_ADDRESS: "pds:8081"
    ports:
      - "8080:8080"
  pds:
    build:
      dockerfile: dev/Dockerfile.pds
      context: .
    networks:
      pds_network:
        aliases:
          - pds
    expose:
      - "8081"
    environment:
      LISTEN_ADDR: ":8081"

networks:
  pds_network: