// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pds.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Country              string    `protobuf:"bytes,4,opt,name=Country,proto3" json:"Country,omitempty"`
	Alias                []string  `protobuf:"bytes,5,rep,name=Alias,proto3" json:"Alias,omitempty"`
	Coordinates          []float32 `protobuf:"fixed32,6,rep,packed,name=Coordinates,proto3" json:"Coordinates,omitempty"`
	Province             string    `protobuf:"bytes,7,opt,name=Province,proto3" json:"Province,omitempty"`
	Timezone             string    `protobuf:"bytes,8,opt,name=Timezone,proto3" json:"Timezone,omitempty"`
	Unlocs               []string  `protobuf:"bytes,9,rep,name=Unlocs,proto3" json:"Unlocs,omitempty"`
	Code                 string    `protobuf:"bytes,10,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80d04e032834ab4, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetCoordinates() []float32 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Ports struct {
	Response             []*Port  `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ports) Reset()         { *m = Ports{} }
func (m *Ports) String() string { return proto.CompactTextString(m) }
func (*Ports) ProtoMessage()    {}
func (*Ports) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80d04e032834ab4, []int{1}
}

func (m *Ports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ports.Unmarshal(m, b)
}
func (m *Ports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ports.Marshal(b, m, deterministic)
}
func (m *Ports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ports.Merge(m, src)
}
func (m *Ports) XXX_Size() int {
	return xxx_messageInfo_Ports.Size(m)
}
func (m *Ports) XXX_DiscardUnknown() {
	xxx_messageInfo_Ports.DiscardUnknown(m)
}

var xxx_messageInfo_Ports proto.InternalMessageInfo

func (m *Ports) GetResponse() []*Port {
	if m != nil {
		return m.Response
	}
	return nil
}

type DeletePortByIDMsg struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePortByIDMsg) Reset()         { *m = DeletePortByIDMsg{} }
func (m *DeletePortByIDMsg) String() string { return proto.CompactTextString(m) }
func (*DeletePortByIDMsg) ProtoMessage()    {}
func (*DeletePortByIDMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80d04e032834ab4, []int{2}
}

func (m *DeletePortByIDMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePortByIDMsg.Unmarshal(m, b)
}
func (m *DeletePortByIDMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePortByIDMsg.Marshal(b, m, deterministic)
}
func (m *DeletePortByIDMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePortByIDMsg.Merge(m, src)
}
func (m *DeletePortByIDMsg) XXX_Size() int {
	return xxx_messageInfo_DeletePortByIDMsg.Size(m)
}
func (m *DeletePortByIDMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePortByIDMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePortByIDMsg proto.InternalMessageInfo

func (m *DeletePortByIDMsg) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type NoParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParams) Reset()         { *m = NoParams{} }
func (m *NoParams) String() string { return proto.CompactTextString(m) }
func (*NoParams) ProtoMessage()    {}
func (*NoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80d04e032834ab4, []int{3}
}

func (m *NoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParams.Unmarshal(m, b)
}
func (m *NoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParams.Marshal(b, m, deterministic)
}
func (m *NoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParams.Merge(m, src)
}
func (m *NoParams) XXX_Size() int {
	return xxx_messageInfo_NoParams.Size(m)
}
func (m *NoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParams.DiscardUnknown(m)
}

var xxx_messageInfo_NoParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Port)(nil), "proto.Port")
	proto.RegisterType((*Ports)(nil), "proto.Ports")
	proto.RegisterType((*DeletePortByIDMsg)(nil), "proto.DeletePortByIDMsg")
	proto.RegisterType((*NoParams)(nil), "proto.NoParams")
}

func init() { proto.RegisterFile("pds.proto", fileDescriptor_f80d04e032834ab4) }

var fileDescriptor_f80d04e032834ab4 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x5d, 0x6a, 0xe3, 0x30,
	0x14, 0x85, 0xf1, 0x6f, 0xec, 0x9b, 0x61, 0x86, 0xb9, 0x0c, 0x83, 0xc8, 0x93, 0x71, 0x29, 0xf5,
	0x53, 0x28, 0xc9, 0x0a, 0xda, 0xf8, 0xc5, 0xd0, 0x06, 0xe3, 0xb6, 0x0b, 0x70, 0xe3, 0x4b, 0x11,
	0x24, 0x52, 0x90, 0xd4, 0x40, 0xba, 0x85, 0x6e, 0xb7, 0x0b, 0x28, 0x92, 0x9d, 0xe0, 0xb6, 0x4f,
	0xba, 0xe7, 0x3b, 0xe2, 0xe8, 0xe8, 0x42, 0xba, 0xef, 0xf4, 0x7c, 0xaf, 0xa4, 0x91, 0x18, 0xb9,
	0x23, 0xff, 0xf0, 0x20, 0xac, 0xa5, 0x32, 0xf8, 0x1b, 0xfc, 0xaa, 0x64, 0x5e, 0xe6, 0x15, 0x69,
	0xe3, 0x57, 0x25, 0x22, 0x84, 0xeb, 0x76, 0x47, 0xcc, 0x77, 0xc4, 0xcd, 0x96, 0xad, 0xb8, 0x39,
	0xb2, 0xa0, 0x67, 0x76, 0x46, 0x06, 0x93, 0x95, 0x7c, 0x15, 0x46, 0x1d, 0x59, 0xe8, 0xf0, 0x49,
	0xe2, 0x3f, 0x88, 0x6e, 0xb6, 0xbc, 0xd5, 0x2c, 0xca, 0x82, 0x22, 0x6d, 0x7a, 0x81, 0x19, 0x4c,
	0x57, 0x52, 0xaa, 0x8e, 0x8b, 0xd6, 0x90, 0x66, 0x71, 0x16, 0x14, 0x7e, 0x33, 0x46, 0x38, 0x83,
	0xa4, 0x56, 0xf2, 0xc0, 0xc5, 0x86, 0xd8, 0xc4, 0x45, 0x9e, 0xb5, 0xf5, 0x1e, 0xf9, 0x8e, 0xde,
	0xa4, 0x20, 0x96, 0xf4, 0xde, 0x49, 0xe3, 0x7f, 0x88, 0x9f, 0xc4, 0x56, 0x6e, 0x34, 0x4b, 0xdd,
	0x83, 0x83, 0x72, 0xad, 0x65, 0x47, 0x0c, 0x86, 0xd6, 0xb2, 0xa3, 0xfc, 0x1a, 0x22, 0xfb, 0x6b,
	0x8d, 0x57, 0x90, 0x28, 0xd2, 0x7b, 0x29, 0x34, 0x31, 0x2f, 0x0b, 0x8a, 0xe9, 0x62, 0xda, 0x2f,
	0x68, 0x6e, 0xfd, 0xe6, 0x6c, 0xe6, 0x17, 0xf0, 0xb7, 0xa4, 0x2d, 0x19, 0xb2, 0xfc, 0xf6, 0x58,
	0x95, 0xf7, 0xfa, 0xe5, 0xfb, 0xd2, 0x72, 0x80, 0x64, 0x2d, 0xeb, 0x56, 0xb5, 0x3b, 0xbd, 0x78,
	0xf7, 0x20, 0xad, 0xcb, 0x07, 0x52, 0x07, 0xbe, 0x21, 0xcc, 0x21, 0xae, 0x84, 0x26, 0x65, 0x70,
	0x9c, 0x3f, 0x1b, 0x0b, 0xbc, 0x84, 0xf0, 0x8e, 0x6b, 0x83, 0x7f, 0x06, 0x78, 0x8a, 0x9a, 0xfd,
	0x1a, 0xdd, 0xd2, 0xb8, 0x04, 0xe8, 0x9b, 0xd8, 0x16, 0xc8, 0x06, 0xef, 0x47, 0xb9, 0x2f, 0xd9,
	0xcf, 0xb1, 0x9b, 0x97, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0xc0, 0xd1, 0x6b, 0x02, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PDServiceClient is the client API for PDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PDServiceClient interface {
	Insert(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Port, error)
	List(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (*Ports, error)
	DeleteByID(ctx context.Context, in *DeletePortByIDMsg, opts ...grpc.CallOption) (*Port, error)
}

type pDServiceClient struct {
	cc *grpc.ClientConn
}

func NewPDServiceClient(cc *grpc.ClientConn) PDServiceClient {
	return &pDServiceClient{cc}
}

func (c *pDServiceClient) Insert(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/proto.PDService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDServiceClient) List(ctx context.Context, in *NoParams, opts ...grpc.CallOption) (*Ports, error) {
	out := new(Ports)
	err := c.cc.Invoke(ctx, "/proto.PDService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDServiceClient) DeleteByID(ctx context.Context, in *DeletePortByIDMsg, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/proto.PDService/DeleteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDServiceServer is the server API for PDService service.
type PDServiceServer interface {
	Insert(context.Context, *Port) (*Port, error)
	List(context.Context, *NoParams) (*Ports, error)
	DeleteByID(context.Context, *DeletePortByIDMsg) (*Port, error)
}

// UnimplementedPDServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPDServiceServer struct {
}

func (*UnimplementedPDServiceServer) Insert(ctx context.Context, req *Port) (*Port, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (*UnimplementedPDServiceServer) List(ctx context.Context, req *NoParams) (*Ports, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedPDServiceServer) DeleteByID(ctx context.Context, req *DeletePortByIDMsg) (*Port, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByID not implemented")
}

func RegisterPDServiceServer(s *grpc.Server, srv PDServiceServer) {
	s.RegisterService(&_PDService_serviceDesc, srv)
}

func _PDService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PDService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).Insert(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PDService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).List(ctx, req.(*NoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDService_DeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePortByIDMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDServiceServer).DeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PDService/DeleteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDServiceServer).DeleteByID(ctx, req.(*DeletePortByIDMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _PDService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PDService",
	HandlerType: (*PDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _PDService_Insert_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PDService_List_Handler,
		},
		{
			MethodName: "DeleteByID",
			Handler:    _PDService_DeleteByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pds.proto",
}
